version: '3'
services:
  app:
    build: ./
    container_name: node-server
    ports:
      - '3000:80'
    volumes:
      - /usr/app
  mtail:
    build: ./mtail/
    container_name: mtail
    ports:
      - 3903:3903
    command:
      - -logtostderr
      - -progs
      - /progs/app.mtail
      - -logs
      - /usr/app/app.log
    volumes:
      - ./progs/app.mtail:/progs/app.mtail:ro
    volumes_from:
      - app:ro
